import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import App from './app/page';
import {ForgotPassword} from './app/recovery';
import {emojis} from './lib/model';
import './app/globals.css';
import './app/mobile-refresh.css';
function Gate(){const [ready,setReady]=useState(false),[actor,setActor]=useState<any>(null),[mode,setMode]=useState('login'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[email,setEmail]=useState(''),[name,setName]=useState(''),[avatar,setAvatar]=useState('😎'),[invite,setInvite]=useState(''),[claim,setClaim]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[adminPassword,setAdminPassword]=useState(''),[legacy,setLegacy]=useState<any[]>([]),[code,setCode]=useState('');
async function refresh(){const r=await fetch('/api/session');if(!r.ok)throw Error('Connexion impossible.');const d=await r.json();setActor(d.actor);setReady(true);}
useEffect(()=>{refresh().catch(()=>{setReady(true);setError('Connexion au serveur impossible. Réessaie.');});},[]);
async function request(path:string,body:any){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);return d;}
if(!ready)return <div className="loading">On retrouve la bande…</div>;if(actor)return <App actor={actor}/>;
return <main className="login-shell"><div className="login-mark">🤞</div><h1>Pari à Long Terme<span className="coral">.</span></h1><p className="muted">Ton personnage, tes paris, ton mot de passe.</p><div className="actions"><button className={mode==='login'?'primary':'secondary'} onClick={()=>{setMode('login');setError('');}}>Se connecter</button><button className={mode==='register'?'primary':'secondary'} onClick={()=>{setMode('register');setError('');}}>Créer mon personnage</button></div>{mode==='forgot'?<ForgotPassword back={()=>{setMode('login');setError('');}}/>:<form className="panel" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{if(mode==='register'&&password!==confirm)throw Error('Les mots de passe ne correspondent pas.');await request(mode==='login'?'/api/session':'/api/accounts',mode==='login'?{username,password}:{action:'register',username,password,name,avatar,invite,claim,email});if(mode==='register')location.hash='profile';setPassword('');await refresh();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>
{mode==='register'&&<><label className="field">Adresse e-mail<input required type="email" maxLength={254} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/><small>À vérifier dans Profil après l’inscription pour récupérer ton mot de passe.</small></label><label className="field">Ton prénom<input required maxLength={40} value={name} onChange={e=>setName(e.target.value)}/></label><label className="field">Ton personnage<select value={avatar} onChange={e=>setAvatar(e.target.value)}>{emojis.map(x=><option key={x}>{x}</option>)}</select></label><p className="small-text muted">Tu pourras aussi importer ta photo depuis ton profil.</p><label className="field">Code d’invitation de la bande<input required autoComplete="off" type="password" value={invite} onChange={e=>setInvite(e.target.value)}/></label><label className="field">Code de reprise d’un ancien personnage <span>facultatif</span><input autoComplete="off" value={claim} onChange={e=>setClaim(e.target.value)}/></label></>}
<label className="field">Identifiant<input required autoComplete="username" pattern="[a-zA-Z0-9._-]{3,32}" minLength={3} maxLength={32} placeholder="ex. ewan27" value={username} onChange={e=>setUsername(e.target.value)}/></label><label className="field">Mot de passe personnel<input autoComplete={mode==='register'?'new-password':'current-password'} type="password" required minLength={mode==='register'?12:1} maxLength={256} value={password} onChange={e=>setPassword(e.target.value)}/></label>{mode==='register'&&<label className="field">Confirmer le mot de passe<input type="password" required autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/><small>12 caractères minimum. Une phrase est facile à retenir.</small></label>}{error&&<p role="alert" className="inline-warning">{error}</p>}<button className="primary full" disabled={busy}>{busy?'Un instant…':mode==='login'?'Retrouver mes paris':'Créer mon personnage'}</button>{mode==='login'&&<button type="button" className="text-btn forgot-link" onClick={()=>{setMode('forgot');setError('');setPassword('');}}>Mot de passe oublié ?</button>}</form>}
<details className="panel"><summary>Administration · anciens profils et accès oubliés</summary><p className="muted small-text">Réservé à l’administrateur. Un code de reprise lie un ancien personnage au nouveau compte et conserve ses paris.</p><label className="field">Mot de passe administrateur<input type="password" autoComplete="off" value={adminPassword} onChange={e=>setAdminPassword(e.target.value)}/></label><button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{setLegacy((await request('/api/accounts',{action:'legacy',adminPassword})).people);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Afficher les personnages à reprendre</button>{legacy.map(p=><div className="setting-row" key={p.id}><span>{p.name}</span><button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{const d=await request('/api/accounts',{action:'claimCode',adminPassword,personId:p.id});setCode(p.name+' : '+d.code);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Créer un code</button></div>)}{code&&<p className="claim-code">{code}<br/><small>À transmettre uniquement à cette personne. Valable 24 heures, utilisable une fois.</small></p>}<p className="small-text muted">Pour réinitialiser un accès, saisis l’identifiant et le nouveau mot de passe personnel dans le formulaire ci-dessus, puis utilise ce bouton.</p><button className="secondary" disabled={busy} onClick={async()=>{if(!window.confirm('Réinitialiser ce mot de passe et fermer toutes les sessions de ce compte ?'))return;setBusy(true);try{await request('/api/accounts',{action:'resetPassword',adminPassword,username,password});setError('Mot de passe réinitialisé. Tu peux te connecter.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Réinitialiser l’accès</button></details></main>;
}
createRoot(document.getElementById('root')!).render(<Gate/>);
