import {useState} from 'react';
import {Bet,Person,Stake,stakeText} from '../lib/model';
const stakeKinds:[Stake['type'],string][]=[['dare','🎯 Gage'],['reward','🎁 Récompense'],['money','💰 Argent'],['other','✨ Autre'],['none','🤝 Pour le plaisir']];
export function Negotiation({bet,people,personId,mutate,busy}:{bet:Bet;people:Person[];personId:string;mutate:(x:any)=>Promise<boolean>;busy:boolean}){
 const [editing,setEditing]=useState(false),[stake,setStake]=useState<Stake>({type:'dare',text:''}),[draftRevision,setDraftRevision]=useState(bet.revision),[joining,setJoining]=useState<string|null>(null);
 const mine=bet.members.find(m=>m.personId===personId),accepted=bet.acceptances.includes(personId),refused=bet.refusals.includes(personId),owner=bet.creator_id===personId;
 const both=bet.members.some(m=>m.side==='for')&&bet.members.some(m=>m.side==='against');
 const all=both&&bet.members.every(m=>bet.acceptances.includes(m.personId));
 const send=(action:string,extra:any={})=>mutate({action,id:bet.id,revision:bet.revision,...extra});
 const history=<details className="proposal-history"><summary>Voir les propositions précédentes</summary>{bet.proposals.map(p=><p key={p.revision}><strong>{people.find(x=>x.id===p.person_id)?.name}</strong><br/>{stakeText(p.stake)}</p>)}</details>;
 if(bet.status!=='active')return bet.proposals.length?<section className="negotiation">{history}</section>:null;
 if(bet.phase==='locked')return <section className="negotiation"><p className="agreement-note">🤝 Pari lancé · camps et enjeu fixés.</p>{bet.proposals.length>0&&history}</section>;
 const stale=draftRevision!==bet.revision;
 function edit(){setStake({...bet.stake});setDraftRevision(bet.revision);setEditing(true);}
 return <section className="negotiation simple-negotiation">
 {mine?<div className={'fixed-camp '+mine.side}><span>{mine.side==='for'?'👍 Tu es Pour':'👎 Tu es Contre'}</span><small>Camp définitif</small></div>:<div className="join-choice"><h3>Tu prends le pari ?</h3><p className="muted small-text">Ton camp sera définitif. L’enjeu se discute ensuite.</p>{joining?<div className="join-confirm"><strong>Rejoindre le camp {joining==='for'?'Pour':'Contre'} ?</strong><p className="small-text muted">Ce choix est définitif. Tu pourras accepter ou refuser l’enjeu séparément.</p><div className="actions"><button className="secondary" disabled={busy} onClick={()=>setJoining(null)}>Retour</button><button className="primary" disabled={busy} onClick={async()=>{if(await send('join',{side:joining}))setJoining(null);}}>Confirmer mon camp</button></div></div>:<div className="actions"><button className="secondary side-for" disabled={busy} onClick={()=>setJoining('for')}>👍 Pour</button><button className="secondary side-against" disabled={busy} onClick={()=>setJoining('against')}>👎 Contre</button></div>}</div>}
 {editing&&mine?<form className="proposal-form" onSubmit={async e=>{e.preventDefault();if(stale)return;if(await send('propose',{stake,revision:draftRevision}))setEditing(false);}}><h3>Que proposes-tu ?</h3><div className="stake-kind-choices" role="group" aria-label="Type d’enjeu">{stakeKinds.map(([type,label])=><button type="button" key={type} aria-pressed={stake.type===type} className={stake.type===type?'chosen':''} onClick={()=>setStake(type==='money'?{type,amount:20,currency:'EUR'}:{type,text:''})}>{label}</button>)}</div>{stake.type==='money'?<><div className="two-fields"><label className="field">Montant<input required type="number" min="0.01" max="1000000000000" step="0.01" value={stake.amount||''} onChange={e=>setStake({...stake,amount:Number(e.target.value)})}/></label><label className="field">Devise<select value={stake.currency} onChange={e=>setStake({...stake,currency:e.target.value})}>{['EUR','XPF','USD'].map(c=><option key={c}>{c}</option>)}</select></label></div><p className="small-text muted">Engagement mémorisé, sans paiement dans l’application.</p></>:stake.type!=='none'&&<label className="field">{stake.type==='dare'?'Le gage des perdants':stake.type==='reward'?'La récompense des gagnants':'Ton idée'}<textarea autoFocus required maxLength={500} rows={3} value={stake.text||''} onChange={e=>setStake({...stake,text:e.target.value})} placeholder="Les perdants offrent une pizza aux gagnants."/></label>}<p className="small-text muted">En proposant, tu donnes ton accord. Les autres doivent accepter.</p>{stale&&<p role="alert" className="inline-warning">Le pari a évolué. Ferme ce formulaire pour consulter la nouvelle proposition.</p>}<div className="actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setEditing(false)}>Annuler</button><button className="primary" disabled={busy||stale}>{busy?'Envoi…':'Proposer cet enjeu'}</button></div></form>:<div className="current-proposal"><span className="eyebrow">L’ENJEU PROPOSÉ</span><h3 className="prewrap">{stakeText(bet.stake)}</h3>{mine&&<>{accepted?<p className="consent-feedback accepted" role="status">✓ Tu as accepté cet enjeu.</p>:refused?<p className="consent-feedback refused" role="status">Tu as refusé cet enjeu. Ton camp reste inchangé.</p>:<p className="muted small-text">Cet enjeu te convient ?</p>}<div className="actions">{!accepted&&<button className="primary" disabled={busy} onClick={()=>send('accept')}>Accepter</button>}<button className="secondary" disabled={busy} onClick={edit}>Proposer autre chose</button></div>{!refused&&<button className="text-btn decline-stake" disabled={busy} onClick={()=>send('reject')}>{accepted?'Finalement, refuser cet enjeu':'Refuser cet enjeu'}</button>}</>}</div>}
 <details className="agreement-progress"><summary>{bet.acceptances.length}/{bet.members.length} participants ont accepté {bet.refusals.length>0&&`· ${bet.refusals.length} refus`}</summary><ul className="consent-list">{bet.members.map(m=><li key={m.personId}>{people.find(p=>p.id===m.personId)?.name}<span className={bet.refusals.includes(m.personId)?'refused':''}>{bet.acceptances.includes(m.personId)?'✓ Accepté':bet.refusals.includes(m.personId)?'Refusé':'En attente'}</span></li>)}</ul></details>
 {!editing&&owner&&<div className="start-agreement"><p className="small-text muted">{all?'Tout le monde est d’accord. Prêt à lancer le pari ?':!both?'Le pari attend encore un participant dans l’autre camp.':'Le pari pourra être lancé quand tout le monde aura accepté l’enjeu.'}</p><button className="primary full" disabled={busy||!all} onClick={()=>{if(window.confirm('Lancer le pari ? L’enjeu sera fixé et les inscriptions seront fermées.'))send('lock');}}>Lancer le pari</button></div>}
 <details className="agreement-help"><summary>Comment ça marche ?</summary><p>Les camps sont définitifs. Une nouvelle proposition ou un nouvel arrivant demande un nouvel accord sur l’enjeu. Un refus bloque le lancement.</p></details>{history}</section>;
}

export function PasswordSettings(){const [currentPassword,setCurrent]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <details className="panel"><summary>Modifier mon mot de passe</summary><form onSubmit={async e=>{e.preventDefault();setError('');if(password!==confirm){setError('Les mots de passe ne correspondent pas.');return;}setBusy(true);try{const r=await fetch('/api/accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'password',currentPassword,password})});const d=await r.json();if(!r.ok)throw Error(d.error);location.reload();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label className="field">Mot de passe actuel<input required type="password" autoComplete="current-password" value={currentPassword} onChange={e=>setCurrent(e.target.value)}/></label><label className="field">Nouveau mot de passe<input required minLength={12} maxLength={256} type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="field">Confirmer<input required type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><p className="small-text muted">Tu devras te reconnecter sur tes appareils.</p>{error&&<p role="alert">{error}</p>}<button className="primary" disabled={busy}>Enregistrer le nouveau mot de passe</button></form></details>;}
