import {useEffect,useState} from 'react';
async function request(body:any){const r=await fetch('/api/recovery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'Connexion impossible.');return d;}
export function ForgotPassword({back}:{back:()=>void}){
 const [email,setEmail]=useState(''),[challenge,setChallenge]=useState(''),[code,setCode]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[sentAt,setSentAt]=useState(0);
 async function send(){if(Date.now()-sentAt<60000){setError('Attends une minute avant de renvoyer un code.');return;}setBusy(true);setError('');try{const d=await request({action:'requestReset',email});setChallenge(d.challengeId);setCode('');setMessage(d.message);setSentAt(Date.now());}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel recovery-panel"><h2>{done?'Mot de passe modifié':'Mot de passe oublié ?'}</h2>{done?<><p>Tes anciennes sessions ont été fermées. Connecte-toi avec ton nouveau mot de passe.</p><button className="primary full" onClick={back}>Revenir à la connexion</button></>:<><p className="muted">Utilise l’adresse e-mail vérifiée dans ton profil.</p>{!challenge?<form onSubmit={e=>{e.preventDefault();send();}}><label className="field">Adresse e-mail<input type="email" required maxLength={254} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="primary full" disabled={busy}>{busy?'Envoi…':'Recevoir un code'}</button></form>:<><p role="status" className="agreement-note">{message}</p><form onSubmit={async e=>{e.preventDefault();setError('');if(password!==confirm){setError('Les mots de passe ne correspondent pas.');return;}setBusy(true);try{await request({action:'resetPassword',challengeId:challenge,code,password});setPassword('');setConfirm('');setDone(true);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label className="field">Code reçu par e-mail<input required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/><small>6 chiffres · valable 10 minutes</small></label><label className="field">Nouveau mot de passe<input required type="password" minLength={12} maxLength={256} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="field">Confirmer le mot de passe<input required type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button className="primary full" disabled={busy}>{busy?'Vérification…':'Enregistrer mon nouveau mot de passe'}</button></form><div className="actions"><button className="text-btn" disabled={busy} onClick={send}>Renvoyer un code</button><button className="text-btn" disabled={busy} onClick={()=>{setChallenge('');setError('');setSentAt(0);}}>Changer d’adresse</button></div></>}{error&&<p role="alert" className="inline-warning">{error}</p>}<button className="text-btn" disabled={busy} onClick={back}>Retour à la connexion</button><p className="small-text muted">Sans adresse vérifiée, contacte l’administrateur de la bande pour retrouver ton accès.</p></>}</section>;
}
export function EmailSettings(){
 const [email,setEmail]=useState(''),[verified,setVerified]=useState(false),[current,setCurrent]=useState(''),[password,setPassword]=useState(''),[challenge,setChallenge]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[configured,setConfigured]=useState(false),[ready,setReady]=useState(false);
 useEffect(()=>{fetch('/api/recovery').then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setEmail(d.email||'');setCurrent(d.email||'');setVerified(d.email_verified);setConfigured(d.configured);setReady(true);}).catch(()=>setError('Impossible de charger ton adresse. Actualise la page.'));},[]);
 return <details className="panel recovery-panel email-settings"><summary>Adresse de récupération</summary><p className="muted">Cette adresse reste privée. Elle permet de recevoir un code si tu oublies ton mot de passe.</p>{verified&&<p className="agreement-note">✓ Adresse vérifiée : {current}</p>}{ready&&!configured&&<p className="inline-warning">L’administrateur doit encore configurer l’envoi d’e-mails.</p>}{!verified&&<p className="small-text muted">Confirme ton adresse pour activer la récupération par e-mail.</p>}<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setMessage('');try{const d=await request({action:'requestVerification',email,currentPassword:password});setChallenge(d.challengeId);setCode('');setMessage(d.message);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label className="field">Adresse e-mail<input required type="email" maxLength={254} autoComplete="email" value={email} onChange={e=>{setEmail(e.target.value);setChallenge('');}}/></label><label className="field">Ton mot de passe actuel<input required type="password" maxLength={256} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="secondary" disabled={busy||!configured}>{busy?'Un instant…':challenge?'Renvoyer le code':'Recevoir un code de vérification'}</button></form>{challenge&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await request({action:'confirmVerification',challengeId:challenge,code});setCurrent(email.trim().toLowerCase());setVerified(true);setChallenge('');setPassword('');setMessage('Adresse vérifiée. Tu peux maintenant récupérer ton accès par e-mail.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label className="field">Code reçu par e-mail<input required pattern="[0-9]{6}" inputMode="numeric" maxLength={6} autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/></label><button className="primary" disabled={busy}>Confirmer mon adresse</button></form>}{message&&<p role="status" className="agreement-note">{message}</p>}{error&&<p role="alert" className="inline-warning">{error}</p>}</details>;
}
